CREATE TABLE pet (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT NOT NULL,
    idade_mes BIGINT NOT NULL,
    idade_ano BIGINT NOT NULL,
    especie VARCHAR(80) NOT NULL,
    cor VARCHAR(255) NOT NULL,
    sexo VARCHAR(1),
    status VARCHAR(80) NOT NULL,
    register_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);