spring:
  application:
    name: me-audota
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: meaudota-db-pool
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:me#4ud0t4}
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}